version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    ports:
      - 3000:3000
    restart: unless-stopped
    command: ['npm', 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '3000']