name: CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Download Packages
        run: npm install

      - name: Build Website
        run: npm run build

      - name: Deploy Live to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CATALOGO_PI }}'
          channelId: live
          projectId: catalogo-pi
